/**
 * SWM Smart Guide — Tour Flow Definitions
 * Mapping from TVL_SWM_UserFlow_A_to_Z.md
 * Each flow = a sequence of steps guiding the user through a business process
 */

export const TOUR_CATEGORIES = [
  { id: 'setup', label: 'Thiết lập hệ thống', icon: 'Settings' },
  { id: 'inbound', label: 'Nhập kho (Inbound)', icon: 'ArrowDownToLine' },
  { id: 'outbound', label: 'Xuất kho (Outbound)', icon: 'ArrowUpFromLine' },
  { id: 'warehouse', label: 'Vận hành kho', icon: 'Warehouse' },
  { id: 'billing', label: 'Thanh toán & Billing', icon: 'FileText' },
  { id: 'reporting', label: 'Báo cáo & Kiểm soát', icon: 'BarChart3' },
]

export const TOUR_FLOWS = [
  // ─── FLOW 1: Setup Master Data (WH_ADMIN) ───
  {
    id: 'setup-master-data',
    title: 'Thiết lập Master Data',
    description: 'Chuẩn bị dữ liệu nền: Owner, Vendor, Item, Warehouse, Zone, Location, UoM, Vehicle Type — bắt buộc trước khi vận hành.',
    role: 'WH_ADMIN',
    category: 'setup',
    estimatedMinutes: 8,
    steps: [
      {
        id: 'smd-1',
        route: '/app/master-data/owners',
        target: '.section-title',
        title: '① Quản lý Owner (Chủ hàng)',
        description: 'Đây là trang quản lý danh sách Owner. Mỗi Owner đại diện cho 1 chủ hàng — tồn kho và billing đều tách biệt theo Owner.',
        placement: 'bottom',
      },
      {
        id: 'smd-2',
        route: '/app/master-data/owners',
        target: '[data-tour="add-btn"], button:has(> svg)',
        fallbackTarget: '.flex.items-center.justify-between button',
        title: '② Tạo Owner mới',
        description: 'Bấm nút "Add Owner" để tạo chủ hàng mới. Cần nhập: Code (duy nhất), Name, Tax Code, Contact.',
        placement: 'bottom',
      },
      {
        id: 'smd-3',
        route: '/app/master-data/items',
        target: '.section-title',
        title: '③ Quản lý Item / SKU',
        description: 'Trang quản lý hàng hóa. Mỗi Item cần khai báo: cargo_form (BULK/BAGGED), tolerance % cho inbound & outbound, is_catch_weight.',
        placement: 'bottom',
      },
      {
        id: 'smd-4',
        route: '/app/master-data/warehouses',
        target: '.section-title',
        title: '④ Quản lý Warehouse',
        description: 'Tạo và quản lý kho. Mỗi kho có mã riêng, phân vùng zones, và danh sách locations bên trong.',
        placement: 'bottom',
      },
      {
        id: 'smd-5',
        route: '/app/master-data/vendors',
        target: '.section-title',
        title: '⑤ Quản lý Vendor (Nhà cung cấp)',
        description: 'Khai báo danh sách nhà cung cấp / đối tác vận chuyển.\n\nVendor dùng trong: Receipt (nguồn hàng), Shipment (đơn vị vận chuyển).',
        placement: 'bottom',
      },
      {
        id: 'smd-6',
        route: '/app/master-data/zones',
        target: '.section-title',
        title: '⑥ Quản lý Zone (Phân vùng kho)',
        description: 'Zone = phân vùng logic trong kho.\nMỗi zone chứa nhiều locations.\n\nVD: Zone A (hàng xá), Zone B (hàng bao), Zone C (staging).',
        placement: 'bottom',
      },
      {
        id: 'smd-7',
        route: '/app/master-data/locations',
        target: '.section-title',
        title: '⑦ Quản lý Location (Vị trí kho)',
        description: 'Tạo vị trí trong kho. Mỗi location có type: RECEIVING (nhận hàng), STORAGE (lưu kho), STAGING (chuẩn bị xuất), SHIPPING (xuất).\n\n⚠️ Putaway chỉ được đưa vào location type = STORAGE.',
        placement: 'bottom',
      },
      {
        id: 'smd-8',
        route: '/app/master-data/uoms',
        target: '.section-title',
        title: '⑧ Đơn vị tính (UoM)',
        description: 'Quản lý đơn vị đo lường: KG, MT (Metric Ton), BAG, JUMBO.\n\nMỗi Item gắn với 1 UoM chính.\nCân tính theo KG → convert sang MT khi cần.',
        placement: 'bottom',
      },
      {
        id: 'smd-9',
        route: '/app/master-data/vehicle-types',
        target: '.section-title',
        title: '⑨ Loại phương tiện (Vehicle Types)',
        description: 'Khai báo loại xe: Xe tải 5T, 10T, 20T, Container 20ft, 40ft.\n\nDùng trong Receipt/Shipment để gắn với chuyến xe.',
        placement: 'bottom',
      },
      {
        id: 'smd-10',
        route: '/app/master-data/inventory-statuses',
        target: '.section-title',
        title: '⑩ Trạng thái tồn kho',
        description: 'Hệ thống có 4 trạng thái: AVAILABLE (có thể xuất), BLOCKED (bị giữ), DAMAGED (hư hỏng), IN_TRANSIT (đang vận chuyển).\n\nChỉ hàng AVAILABLE mới được allocate cho outbound.',
        placement: 'bottom',
      },
      {
        id: 'smd-11',
        route: '/app/settings/reason-codes',
        target: '.page-section, .app-main > div',
        title: '⑪ Cấu hình Reason Code',
        description: 'Reason Code dùng cho mọi thao tác ngoại lệ: manual weight, cancel receipt, inventory adjustment, override exception.\n\nDanh sách go-live tối thiểu: MOISTURE_LOSS, SCALE_CALIBRATION, LOADING_LEFTOVER, DAMAGE, SHRINKAGE...',
        placement: 'bottom',
      },
      {
        id: 'smd-12',
        route: '/app/settings/number-sequences',
        target: '.page-section, .app-main > div',
        title: '⑫ Number Sequence',
        description: 'Cấu hình chuỗi số tự động cho chứng từ.\nFormat: PREFIX-YYYYMMDD-SEQNUM (VD: RCV-20260315-000001).\nScope PER_WAREHOUSE, daily reset.\n\n✅ Setup xong Master Data — hệ thống sẵn sàng vận hành!',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 2: Setup Billing (WH_ADMIN / BILLING_OFC) ───
  {
    id: 'setup-billing',
    title: 'Thiết lập Billing & Rate Card',
    description: 'Cấu hình hợp đồng, biểu phí lưu kho, xử lý, đóng bao cho từng Owner.',
    role: 'WH_ADMIN',
    category: 'setup',
    estimatedMinutes: 4,
    steps: [
      {
        id: 'sb-1',
        route: '/app/billing/rate-cards',
        target: '.section-title',
        title: '① Trang Rate Cards & Contracts',
        description: 'Đây là nơi quản lý hợp đồng và biểu phí. Mỗi Owner có 1 contract active tại 1 thời điểm.',
        placement: 'bottom',
      },
      {
        id: 'sb-2',
        route: '/app/billing/rate-cards',
        target: 'button',
        title: '② Tạo Contract mới',
        description: 'Bấm "Create Contract" → nhập: Owner, ngày hiệu lực, free days (số ngày miễn phí lưu kho).\n\nContract mới ở trạng thái DRAFT.',
        placement: 'bottom',
      },
      {
        id: 'sb-3',
        route: '/app/billing/rate-cards',
        target: '.wrs-card',
        title: '③ Thêm Fee Lines',
        description: 'Trong contract, thêm các dòng phí:\n• Storage rate / MT / ngày\n• Handling rate inbound\n• Handling rate outbound\n• Bagging rate\n\nRate khác nhau theo cargo_form: BULK=21K/MT, BAGGED_50KG=28K/MT, JUMBO=32K/MT.',
        placement: 'bottom',
      },
      {
        id: 'sb-4',
        route: '/app/billing/rate-cards',
        target: '.wrs-card',
        title: '④ Activate Contract',
        description: 'Sau khi review đủ fee lines → Activate contract.\n\n⚠️ Hệ thống sẽ kiểm tra: không được overlap date range với contract đang active của cùng Owner.\n\n✅ Billing setup hoàn tất!',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 3: Admin & Phân quyền (ADMIN) ───
  {
    id: 'admin-settings',
    title: 'Quản trị hệ thống & Phân quyền',
    description: 'Dashboard tổng quan, quản lý vai trò, phân quyền, governance policies, và system logs.',
    role: 'ADMIN',
    category: 'setup',
    estimatedMinutes: 5,
    steps: [
      {
        id: 'adm-1',
        route: '/app',
        target: '.page-section, .app-main > div',
        title: '① Dashboard tổng quan',
        description: '🏠 Trang chủ sau khi đăng nhập.\n\nHiển thị KPI nhanh: tổng tồn kho, số receipt/shipment hôm nay, alerts, warehouse utilization.\n\nTừ đây navigate đến bất kỳ module nào.',
        placement: 'bottom',
      },
      {
        id: 'adm-2',
        route: '/app/settings/roles',
        target: '.page-section, .app-main > div',
        title: '② Quản lý Roles (Vai trò)',
        description: '👥 Hệ thống có các vai trò chính:\n• ADMIN — toàn quyền hệ thống\n• WH_ADMIN — quản trị kho, master data\n• WH_MANAGER — vận hành, approval\n• WH_KEEPER — thao tác kho, mobile\n• WB_OPERATOR — trạm cân\n• BILLING_OFC — tính phí\n• OPS_SUPER — giám sát, báo cáo',
        placement: 'bottom',
      },
      {
        id: 'adm-3',
        route: '/app/settings/permissions',
        target: '.page-section, .app-main > div',
        title: '③ Quản lý Permissions (Quyền hạn)',
        description: '🔐 Phân quyền chi tiết cho từng role:\n• Module-level access (read/write/admin)\n• Action-level: approve, cancel, manual_weight, force_approve\n• Data-level: per warehouse, per owner\n\n⚠️ Principle of least privilege — chỉ cấp quyền cần thiết.',
        placement: 'bottom',
      },
      {
        id: 'adm-4',
        route: '/app/settings/governance',
        target: '.page-section, .app-main > div',
        title: '④ Governance Policies',
        description: '📜 Chính sách vận hành:\n• Tolerance % mặc định cho inbound/outbound\n• Max re-weigh attempts (default: 3)\n• Approval workflow rules\n• Data retention policy (7 năm)\n• Password policy, session timeout',
        placement: 'bottom',
      },
      {
        id: 'adm-5',
        route: '/app/settings/logs',
        target: '.page-section, .app-main > div',
        title: '⑤ System Logs',
        description: '📋 Log hệ thống:\n• Login/Logout events\n• API call logs\n• Error logs\n• Performance metrics\n• Integration sync logs\n\nFilter theo: date, user, severity, module.\n\n✅ Flow Admin & Phân quyền hoàn tất!',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 4: Inbound Standard (WB_OPERATOR) ───
  {
    id: 'inbound-standard',
    title: 'Nhập kho chuẩn (Standard Inbound)',
    description: 'Quy trình xe nhập: ASN → Cân vào (Weigh-In) → Dỡ hàng → Cân ra (Weigh-Out) → Tolerance Check → RECEIVED.',
    role: 'WB_OPERATOR',
    category: 'inbound',
    estimatedMinutes: 6,
    steps: [
      {
        id: 'in-1',
        route: '/app/inbound-operations/receipts',
        target: '.section-title',
        title: '① Danh sách Receipt',
        description: 'Trang quản lý phiếu nhận hàng. Mỗi Receipt = 1 chuyến xe = 1 lần cân.\n\nWH_ADMIN hoặc WH_MANAGER tạo Receipt trước khi xe vào.',
        placement: 'bottom',
      },
      {
        id: 'in-2',
        route: '/app/inbound-operations/receipts',
        target: 'button',
        title: '② Tạo Receipt (PO/ASN)',
        description: 'Bấm "Create Receipt" → nhập: Owner, Item, Expected Qty, Vehicle Number.\n\nReceipt được tạo ở trạng thái DRAFT.',
        placement: 'bottom',
      },
      {
        id: 'in-10',
        route: '/app/inbound-operations/receipts',
        target: '.wrs-card',
        title: '⑩ Close Receipt',
        description: '🔒 WH_MANAGER close receipt sau khi Putaway hoàn tất.\n\nReceipt CLOSED = Immutable (không sửa được).\n\n✅ Flow Inbound Standard hoàn tất!\nHàng đã vào kho → tồn kho tăng → sẵn sàng billing.',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 4: Outbound Full Flow (WB_OPERATOR + WH_KEEPER) ───
  {
    id: 'outbound-full',
    title: 'Xuất kho đầy đủ (Outbound Flow)',
    description: 'Quy trình xuất: Shipment → Allocate → Pick → Cân Tare → Cân Gross từng line → SHIPPED.',
    role: 'WB_OPERATOR',
    category: 'outbound',
    estimatedMinutes: 7,
    steps: [
      {
        id: 'out-1',
        route: '/app/outbound-operations/shipments',
        target: '.section-title',
        title: '① Danh sách Shipment',
        description: 'Quản lý phiếu xuất kho. Mỗi Shipment = 1 chuyến xe.\n\nShipment có thể có nhiều lines (nhiều loại hàng/owner).',
        placement: 'bottom',
      },
      {
        id: 'out-2',
        route: '/app/outbound-operations/shipments',
        target: 'button',
        title: '② Tạo Shipment',
        description: 'Bấm "Create Shipment" → nhập: Owner, Item(s), Expected Qty per line, Vehicle.\n\nShipment tạo ở trạng thái DRAFT → Confirm → CONFIRMED.',
        placement: 'bottom',
      },
      {
        id: 'out-3',
        route: '/app/outbound-operations/allocation',
        target: '.section-title',
        title: '③ Allocation (Phân bổ tồn kho)',
        description: '📊 Hệ thống allocate tồn kho cho shipment:\n• Algorithm: FIFO theo lot_date\n• Chỉ allocate từ stock AVAILABLE\n• Nếu không đủ → FAIL toàn bộ (no partial)\n• reserved_qty tăng → available_qty giảm\n\n→ Shipment: CONFIRMED → ALLOCATED',
        placement: 'bottom',
      },
      {
        id: 'out-4',
        route: '/app/work-execution/queue',
        target: '.section-title',
        title: '④ Pick Work (Lấy hàng)',
        description: '📱 Sau khi ALLOCATED → hệ thống tự tạo Pick Work.\n\nWH_KEEPER trên mobile:\n1. Claim task\n2. Đến source location, scan QR\n3. Lấy hàng, nhập actual_qty\n4. Đưa đến STAGING area\n\n→ Shipment: ALLOCATED → PICKING → PICKED',
        placement: 'bottom',
      },
      {
        id: 'out-5',
        route: '/app/outbound-operations/weighing',
        target: '.section-title',
        title: '⑤ Cân Tare (Xe rỗng)',
        description: '⚖️ WB_OPERATOR tại trạm cân:\n• Xe rỗng vào cân → đọc Tare Weight\n• Bấm "Confirm Tare"\n\n→ Shipment: PICKED → WEIGHING_TARE',
        placement: 'bottom',
      },
      {
        id: 'out-6',
        route: '/app/outbound-operations/weighing',
        target: '.wrs-card',
        title: '⑥ Cân Gross từng Line',
        description: '📦 Xếp hàng line 1 lên xe → cân → net_line_1 = gross_1 − tare\nXếp hàng line 2 → cân → net_line_2 = gross_2 − gross_1\n...\n\n🔑 Flexible sequence: Keeper chọn tự do thứ tự cân.\n⚠️ Line fail tolerance → ghi PENDING_APPROVAL nhưng KHÔNG dừng vòng cân.',
        placement: 'right',
      },
      {
        id: 'out-7',
        route: '/app/outbound-operations/weighing',
        target: '.wrs-card',
        title: '⑦ Kết quả cân',
        description: '✅ Tất cả line PASS → Auto SHIPPED:\n• InventTrans OUTBOUND posted (−qty per line)\n• Billing event OUTBOUND_HANDLING created\n\n⚠️ Có line FAIL → PENDING_APPROVAL:\n• WH_MANAGER nhận notification\n• WB_OPERATOR đã xong việc — xe được phép đi',
        placement: 'bottom',
      },
      {
        id: 'out-8',
        route: '/app/outbound-operations/approvals',
        target: '.section-title',
        title: '⑧ Xử lý Approval (WH_MANAGER)',
        description: '👨‍💼 WH_MANAGER xem từng line fail:\n• Variance %, lịch sử cân, expected vs actual\n\n3 lựa chọn:\n• ✅ Force Approve → SHIPPED (kèm reason_code + audit)\n• ❌ Reject → CANCELLED (allocation released)\n• 🔄 Re-pick → tạo Pick Work mới\n\n✅ Flow Outbound hoàn tất!',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 5: Exception Handling (WH_MANAGER) ───
  {
    id: 'exception-handling',
    title: 'Xử lý ngoại lệ (Exception)',
    description: 'WH_MANAGER xử lý các trường hợp bất thường: tolerance fail, cancel receipt, manual weight, adjustment.',
    role: 'WH_MANAGER',
    category: 'warehouse',
    estimatedMinutes: 4,
    steps: [
      {
        id: 'ex-1',
        route: '/app/outbound-operations/approvals',
        target: '.section-title',
        title: '① Outbound Approval Queue',
        description: 'Danh sách Shipment có line fail tolerance → PENDING_APPROVAL.\n\nWH_MANAGER review và quyết định: Approve / Reject / Re-pick.',
        placement: 'bottom',
      },
      {
        id: 'ex-4',
        route: '/app/inventory-control/adjustments',
        target: '.section-title',
        title: '④ Inventory Adjustment',
        description: '📝 Điều chỉnh tồn kho (hao hụt / tìm thấy hàng):\n• Nhập: Item, Location, Qty (+ hoặc −), Reason Code\n• Post Adjustment → InventTrans ADJUSTMENT created\n• OnHand cập nhật tự động\n\n⚠️ Không cần approval workflow — ghi audit đầy đủ.',
        placement: 'bottom',
      },
      {
        id: 'ex-5',
        route: '/app/inventory-control/cycle-count',
        target: '.section-title',
        title: '⑤ Cycle Count (Kiểm kê)',
        description: '🔍 Quy trình kiểm kê:\n1. WH_MANAGER tạo Count Session, chọn locations\n2. WH_KEEPER đếm (blind count — không thấy system_qty)\n3. WH_MANAGER xem variance = counted − system\n4. Variance = 0 → auto-close | ≠ 0 → chọn reason + approve\n5. InventTrans CYCLE_COUNT_ADJUST posted',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 6: VAS Bagging (WH_KEEPER) ───
  {
    id: 'vas-bagging',
    title: 'Đóng bao VAS (Bagging)',
    description: 'Quy trình đóng bao: Tạo WO → Start Session → Ghi sản lượng → Complete WO → Post 3 InventTrans.',
    role: 'WH_KEEPER',
    category: 'warehouse',
    estimatedMinutes: 4,
    steps: [
      {
        id: 'vas-1',
        route: '/app/vas/work-orders',
        target: '.section-title',
        title: '① Danh sách VAS Work Orders',
        description: 'Quản lý các lệnh đóng bao (VAS Work Order).\n\nMỗi WO gồm: bulk source item, bag type, planned qty, target bags.',
        placement: 'bottom',
      },
      {
        id: 'vas-2',
        route: '/app/vas/work-orders',
        target: 'button',
        title: '② Tạo Work Order',
        description: 'Bấm "Create Work Order" → nhập:\n• Owner, Source Item (bulk), Source Qty\n• Target Qty (bags), Bag Weight\n\n⚠️ Guard: bulk stock ≥ planned_qty → mới cho Confirm.',
        placement: 'bottom',
      },
      {
        id: 'vas-3',
        route: '/app/vas/execution',
        target: '.section-title',
        title: '③ VAS Execution',
        description: '📱 WH_KEEPER thực hiện đóng bao:\n1. Chọn WO → bấm "Start Session"\n2. Nhập ca/shift\n3. Sau mỗi mẻ: nhập actual_qty_kg + bag_count\n4. Khi xong ca → "End Session"',
        placement: 'bottom',
      },
      {
        id: 'vas-4',
        route: '/app/vas/execution',
        target: '.wrs-card',
        title: '④ Complete Work Order',
        description: '✅ Khi WO hoàn tất → bấm "Complete WO"\n\nHệ thống tạo 3 InventTrans atomic:\n• VAS_CONSUME: −bulk (trừ hàng xá)\n• VAS_PRODUCE: +bags (cộng hàng bao)\n• VAS_CONSUME: −packaging (nếu TVL_OWNED)\n\n⚡ Billing event BAGGING_FEE tạo tự động.',
        placement: 'right',
      },
      {
        id: 'vas-5',
        route: '/app/vas/dashboard',
        target: '.section-title',
        title: '⑤ VAS Dashboard',
        description: '📊 Theo dõi tổng quan VAS:\n• Số WO theo trạng thái\n• Progress từng WO\n• Sản lượng theo ca\n\n✅ Flow VAS Bagging hoàn tất!',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 7: Monthly Billing (BILLING_OFC) ───
  {
    id: 'monthly-billing',
    title: 'Tính phí hàng tháng (Billing)',
    description: 'Quy trình billing: Events capture → Generate Debit Note → Review → Approve → Lock → Push ERP.',
    role: 'BILLING_OFC',
    category: 'billing',
    estimatedMinutes: 5,
    steps: [
      {
        id: 'bil-1',
        route: '/app/billing/events',
        target: '.section-title',
        title: '① Billable Events',
        description: '📋 Danh sách billing events tự động capture:\n• Receipt RECEIVED → INBOUND_HANDLING\n• Shipment SHIPPED → OUTBOUND_HANDLING\n• VAS WO COMPLETED → BAGGING_FEE\n• EOD 23:59 → daily_storage_snapshot\n\nEvents chưa có rate card → flag UNBILLED.',
        placement: 'bottom',
      },
      {
        id: 'bil-2',
        route: '/app/billing/invoices',
        target: '.section-title',
        title: '② Debit Note Management',
        description: 'Trang quản lý Debit Note (DN).\n\nDN đi qua: DRAFT → REVIEWED → APPROVED → LOCKED.\nLOCKED = Immutable (không sửa được).',
        placement: 'bottom',
      },
      {
        id: 'bil-3',
        route: '/app/billing/invoices',
        target: 'button',
        title: '③ Generate Draft Debit Note',
        description: 'Bấm "Create" → chọn Owner + period (tháng).\n\nCharge Calculation Engine chạy:\nevents × rate × day_type_factor\n\nTạo DN DRAFT với charge lines: storage, handling, bagging, VAT 10%.',
        placement: 'bottom',
      },
      {
        id: 'bil-4',
        route: '/app/billing/invoices',
        target: '.wrs-card',
        title: '④ Review Charge Lines',
        description: '🔍 BILLING_OFC review từng dòng phí:\n• Storage fee = qty × rate × days × day_type_factor\n• Handling fee = qty × rate\n• VAT = total × 10%\n\n⚠️ Day type: DAY_OFF=150%, HOLIDAY=200%\n📅 Free days: phí tính từ sau free period.',
        placement: 'bottom',
      },
      {
        id: 'bil-5',
        route: '/app/billing/invoices',
        target: '.wrs-card',
        title: '⑤ Approve & Lock',
        description: '✅ Bấm "Approve" → DN: REVIEWED → APPROVED\n🔒 Bấm "Lock" → DN: APPROVED → LOCKED\n\nChỉ BILLING_OFC mới được Lock.\nSau Lock: DN immutable — không thể sửa.',
        placement: 'bottom',
      },
      {
        id: 'bil-6',
        route: '/app/billing/invoices',
        target: '.wrs-card',
        title: '⑥ Push to ERP',
        description: '📤 Bấm "Push to ERP" → gửi payload qua Integration module.\n\n• Idempotent: DN number = unique key\n• ERP nhận thành công → sync_status = SUCCESS\n• ERP reject → retry tự động',
        placement: 'bottom',
      },
      {
        id: 'bil-7',
        route: '/app/billing/dashboard',
        target: '.section-title',
        title: '⑦ Billing Dashboard',
        description: '📊 Tổng quan billing:\n• Revenue by Owner (chart)\n• DN status breakdown: Draft / Reviewed / Approved / Locked\n• Outstanding vs Collected\n• Monthly trend\n\n✅ Flow Billing hoàn tất!',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 8: Inventory Control (WH_MANAGER) ───
  {
    id: 'inventory-control',
    title: 'Quản lý tồn kho (Inventory Control)',
    description: 'On-Hand, Transactions, Holds, Posting Workbench, Move, Transfer, Status Change, Movement History.',
    role: 'WH_MANAGER',
    category: 'warehouse',
    estimatedMinutes: 6,
    steps: [
      {
        id: 'ic-1',
        route: '/app/inventory-core/on-hand',
        target: '.section-title',
        title: '① Xem tồn kho hiện tại (On-Hand)',
        description: '📦 Tồn kho = SUM(InventTrans).\n\nFilter theo: Item, Owner, Warehouse, Location, Status.\navailable_qty = physical_qty − allocated_qty.',
        placement: 'bottom',
      },
      {
        id: 'ic-1b',
        route: '/app/inventory-core/transactions',
        target: '.section-title',
        title: '② Inventory Transactions (Sổ cái)',
        description: '📜 Toàn bộ InventTrans đã post:\n• Type: RECEIVE, ISSUE, MOVE, TRANSFER, ADJUSTMENT, VAS_CONSUME, VAS_PRODUCE\n• Mỗi dòng: Item, Qty, Direction (+/−), Location, Timestamp\n\nĐây là "source of truth" — OnHand = SUM(InventTrans).',
        placement: 'bottom',
      },
      {
        id: 'ic-1c',
        route: '/app/inventory-core/holds',
        target: '.section-title',
        title: '③ Inventory Holds (Giữ hàng)',
        description: '🔒 Quản lý lệnh giữ hàng (Hold):\n• Hold = block 1 lô hàng cụ thể → không cho xuất\n• Reason: quality issue, dispute, customs\n• Release hold → hàng trở về AVAILABLE\n\nKhác với BLOCKED status: Hold là temporary & trackable.',
        placement: 'bottom',
      },
      {
        id: 'ic-1d',
        route: '/app/inventory-core/workbench',
        target: '.section-title',
        title: '④ Posting Workbench',
        description: '⚙️ Công cụ post thủ công các InventTrans:\n• Dùng khi cần điều chỉnh ngoài flow chuẩn\n• Ghi đầy đủ: reason_code, approved_by\n• Audit trail tự động\n\n⚠️ Chỉ WH_MANAGER có quyền sử dụng.',
        placement: 'bottom',
      },
      {
        id: 'ic-2',
        route: '/app/inventory-control/move-orders',
        target: '.section-title',
        title: '⑤ Move Orders (Di chuyển nội bộ)',
        description: '🔄 Di chuyển hàng giữa các location trong cùng warehouse.\n\nPost 2 InventTrans: −qty source / +qty destination.\nNet zero — tổng tồn không đổi.',
        placement: 'bottom',
      },
      {
        id: 'ic-3',
        route: '/app/inventory-control/transfers',
        target: '.section-title',
        title: '⑥ Transfer Orders (Liên kho)',
        description: '🚛 Chuyển hàng giữa các warehouse:\nCREATED → RELEASED → SHIPPED → IN_TRANSIT → RECEIVED → CLOSED\n\nShip: −qty source (AVAILABLE → IN_TRANSIT)\nReceive: +qty destination (IN_TRANSIT → AVAILABLE)',
        placement: 'bottom',
      },
      {
        id: 'ic-4',
        route: '/app/inventory-control/status-change',
        target: '.section-title',
        title: '⑦ Status Change (Đổi trạng thái)',
        description: '🏷️ Đổi trạng thái tồn kho:\n• AVAILABLE ↔ BLOCKED\n• AVAILABLE ↔ DAMAGED\n\nBắt buộc reason_code.\nChỉ hàng AVAILABLE mới allocate được cho outbound.',
        placement: 'bottom',
      },
      {
        id: 'ic-5',
        route: '/app/inventory-control/history',
        target: '.section-title',
        title: '⑧ Movement History',
        description: '📜 Lịch sử toàn bộ di chuyển hàng:\nRECEIVE, ISSUE, MOVE, TRANSFER, ADJUSTMENT, VAS.\n\nFilter theo: Warehouse, Item, Trans Type, Date range.\n\n✅ Flow Inventory Control hoàn tất!',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 9: Reporting & Audit (OPS_SUPER) ───
  {
    id: 'reporting-audit',
    title: 'Báo cáo & Kiểm toán',
    description: 'Dashboard KPI, báo cáo tồn kho, billing report, audit trail, reconciliation.',
    role: 'OPS_SUPER',
    category: 'reporting',
    estimatedMinutes: 4,
    steps: [
      {
        id: 'rp-1',
        route: '/app/reporting/dashboard',
        target: '.section-title',
        title: '① KPI Dashboard',
        description: '📊 Tổng quan vận hành:\n• On-Hand, Reserved, Movement Trend\n• Warehouse Utilization %\n• RECON-001 Pass Rate\n• Total Owners',
        placement: 'bottom',
      },
      {
        id: 'rp-2',
        route: '/app/reporting/inventory',
        target: '.section-title',
        title: '② Inventory Report',
        description: '📦 Báo cáo tồn kho chi tiết:\n• On-Hand per Owner/Location/Status\n• Aging report\n• Shrinkage = Total Inbound − Total Outbound per SKU',
        placement: 'bottom',
      },
      {
        id: 'rp-3',
        route: '/app/reporting/billing',
        target: '.section-title',
        title: '③ Billing Report',
        description: '💰 Báo cáo doanh thu billing:\n• Revenue per Owner\n• Breakdown theo service type\n• DN count: Draft / Approved / Locked',
        placement: 'bottom',
      },
      {
        id: 'rp-4',
        route: '/app/reporting/reconciliation',
        target: '.section-title',
        title: '④ Reconciliation (Đối soát)',
        description: '🔍 Đối soát 3 chiều: Ledger vs OnHand vs Billing.\n\nChạy hourly, SLA ≤ 5 phút.\nKhông auto-fix — chỉ log + alert.\n\nPass Rate theo dõi liên tục.',
        placement: 'bottom',
      },
      {
        id: 'rp-5',
        route: '/app/reporting/audit',
        target: '.section-title',
        title: '⑤ Audit Trail',
        description: '📋 Lịch sử thao tác toàn hệ thống:\n• Filter: date, user, entity type, action\n• Ghi: entity_id, old/new value, timestamp\n• Retention: 7 năm\n• Append-only — không UPDATE/DELETE',
        placement: 'bottom',
      },
      {
        id: 'rp-6',
        route: '/app/reporting/go-live',
        target: '.section-title',
        title: '⑥ Go-Live Checklist',
        description: '🚀 Checklist trước khi go-live:\n• Master Data đầy đủ? (Owner, Item, Location, Rate Card)\n• Number Sequences configured?\n• Reason Codes đủ?\n• Roles & Permissions assigned?\n• Integration channels HEALTHY?\n• UAT scenarios passed?\n\n✅ Flow Reporting & Go-Live hoàn tất!',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 10: Work Execution chi tiết (WH_KEEPER) ───
  {
    id: 'work-execution-detail',
    title: 'Work Execution chi tiết',
    description: 'Quy trình thực hiện công việc kho: Queue → Claim → Execute → Monitor — dành cho WH_KEEPER và Supervisor.',
    role: 'WH_KEEPER',
    category: 'warehouse',
    estimatedMinutes: 5,
    steps: [
      {
        id: 'we-1',
        route: '/app/work-execution/queue',
        target: '.section-title',
        title: '① Work Queue (Hàng đợi)',
        description: '📋 Danh sách tất cả công việc chờ xử lý:\n• Putaway (nhập kho → đưa vào vị trí)\n• Pick (lấy hàng cho outbound)\n• Move (di chuyển nội bộ)\n• Replenishment (bổ sung)\n\nFilter: Work Type, Priority, Warehouse.\nSắp xếp: Priority > Created Date.',
        placement: 'bottom',
      },
      {
        id: 'we-2',
        route: '/app/work-execution/queue',
        target: '.wrs-card',
        title: '② Claim Task (Nhận việc)',
        description: '✋ WH_KEEPER bấm "Claim" để nhận task:\n• 1 task = 1 người claim (no overlap)\n• Claimed task chuyển sang "My Work"\n• Nếu không hoàn tất trong SLA → tự release về queue\n\nTrên mobile: scan QR để claim nhanh.',
        placement: 'bottom',
      },
      {
        id: 'we-3',
        route: '/app/work-execution/my-work',
        target: '.section-title',
        title: '③ My Work (Việc của tôi)',
        description: '📱 Danh sách task đã claim:\n• Status: CLAIMED → IN_PROGRESS → COMPLETED\n• Hiện thời gian elapsed\n• Bấm "Start" để bắt đầu thực hiện\n\nNếu cần hỗ trợ → bấm "Report Issue" (tạo exception).',
        placement: 'bottom',
      },
      {
        id: 'we-4',
        route: '/app/work-execution/execute',
        target: '.page-section, .app-main > div',
        title: '④ Execute Work (Thực hiện)',
        description: '⚡ Màn hình thực hiện công việc:\n1. Start → WorkLine status = IN_PROGRESS\n2. Scan source location QR\n3. Xác nhận qty (actual vs expected)\n4. Scan destination location QR\n5. Complete → WorkLine COMPLETED\n\n⚠️ Nếu actual ≠ expected → ghi exception + reason_code.\n📍 Mỗi line = 1 InventTrans MOVE posted.',
        placement: 'bottom',
      },
      {
        id: 'we-5',
        route: '/app/work-execution/monitor',
        target: '.section-title',
        title: '⑤ Work Monitor (Giám sát)',
        description: '👁️ Supervisor view — theo dõi toàn bộ work:\n• Real-time: ai đang làm gì, ở đâu\n• SLA tracking: task nào quá hạn\n• Performance: tasks/hour per keeper\n• Re-assign: chuyển task cho người khác\n\n✅ Flow Work Execution hoàn tất!',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 11: Integration & Weighbridge (OPS_SUPER) ───
  {
    id: 'integration-monitoring',
    title: 'Giám sát Integration & Weighbridge',
    description: 'Theo dõi trạm cân, kênh tích hợp, alerts, và ERP sync.',
    role: 'OPS_SUPER',
    category: 'reporting',
    estimatedMinutes: 3,
    steps: [
      {
        id: 'ig-1',
        route: '/app/integration/monitoring',
        target: '.section-title',
        title: '① Integration Monitoring',
        description: '📡 Tổng quan sức khỏe integration:\n• Channel Health (ERP, Scale, Mobile)\n• ERP Sync Stats\n• Mobile Sync Stats',
        placement: 'bottom',
      },
      {
        id: 'ig-2',
        route: '/app/integration/weighbridge',
        target: '.section-title',
        title: '② Weighbridge Logs',
        description: '⚖️ Log toàn bộ lần cân:\n• Gross/Tare/Net weight\n• Vehicle, Timestamp\n• Manual vs Auto entry\n• Devices status',
        placement: 'bottom',
      },
      {
        id: 'ig-3',
        route: '/app/integration/alerts',
        target: '.section-title',
        title: '③ Integration Alerts',
        description: '🔔 Cảnh báo integration:\n• Scale fail, ERP reject, Mobile sync error\n• Severity: HIGH / MEDIUM / LOW\n• Resolve workflow: Acknowledge → Resolution Note → Resolved',
        placement: 'bottom',
      },
      {
        id: 'ig-4',
        route: '/app/integration/channels',
        target: '.section-title',
        title: '④ Integration Channels',
        description: '📊 Trạng thái từng kênh:\n• HEALTHY / DEGRADED / DOWN\n• Uptime %\n• Last ping time\n\n✅ Flow Integration hoàn tất!',
        placement: 'bottom',
      },
    ],
  },

  // ─── FLOW 13: End-to-End Demo ───
  {
    id: 'end-to-end',
    title: '🏆 Demo End-to-End: Nhập kho → Billing',
    description: 'Full flow từ A đến Z: Setup → Inbound → Putaway → Outbound → Billing — đi qua toàn bộ hệ thống.',
    role: 'ALL',
    category: 'setup',
    estimatedMinutes: 12,
    steps: [
      // Phase 1: Setup
      {
        id: 'e2e-1',
        route: '/app/master-data/owners',
        target: '.section-title',
        title: 'Phase 1 — Setup: Tạo Owner',
        description: '👤 WH_ADMIN tạo Owner mới — đại diện cho chủ hàng.\nMọi giao dịch đều gắn với Owner.',
        placement: 'bottom',
      },
      {
        id: 'e2e-2',
        route: '/app/master-data/items',
        target: '.section-title',
        title: 'Phase 1 — Setup: Tạo Item',
        description: '📦 Tạo Item/SKU: cargo_form, tolerance %, is_catch_weight.\nTolerance per owner+item override được default.',
        placement: 'bottom',
      },
      {
        id: 'e2e-3',
        route: '/app/billing/rate-cards',
        target: '.section-title',
        title: 'Phase 1 — Setup: Tạo Contract & Rate Card',
        description: '💰 Tạo contract cho Owner: storage rate, handling rate, free days.\nActivate contract → sẵn sàng tính phí.',
        placement: 'bottom',
      },
      // Phase 2: Inbound
      {
        id: 'e2e-4',
        route: '/app/inbound-operations/receipts',
        target: '.section-title',
        title: 'Phase 2 — Inbound: Tạo Receipt',
        description: '📝 WH_ADMIN tạo Receipt (PO/ASN) trước khi xe nhập.\n1 receipt = 1 xe = 1 lần cân.',
        placement: 'bottom',
      },
      // Phase 3: Putaway
      {
        id: 'e2e-6',
        route: '/app/work-execution/queue',
        target: '.section-title',
        title: 'Phase 3 — Putaway: Work Queue',
        description: '📱 Hệ thống tự tạo Putaway Work.\nWH_KEEPER: Claim → Start → Scan QR → Complete.\nHàng chuyển từ RECEIVING → STORAGE.',
        placement: 'bottom',
      },
      // Phase 4: Outbound
      {
        id: 'e2e-7',
        route: '/app/outbound-operations/shipments',
        target: '.section-title',
        title: 'Phase 4 — Outbound: Tạo Shipment',
        description: '🚛 WH_MANAGER tạo Shipment → Allocate → Pick → Cân.\nMulti-line, flexible sequence.',
        placement: 'bottom',
      },
      {
        id: 'e2e-8',
        route: '/app/outbound-operations/weighing',
        target: '.section-title',
        title: 'Phase 4 — Outbound: Cân xuất',
        description: '⚖️ Tare → Gross per line → Tolerance check.\n✅ All pass → SHIPPED (InventTrans −qty).\n⚠️ Fail → PENDING_APPROVAL → WH_MANAGER review.',
        placement: 'bottom',
      },
      // Phase 5: Billing
      {
        id: 'e2e-9',
        route: '/app/billing/events',
        target: '.section-title',
        title: 'Phase 5 — Billing: Events captured',
        description: '📋 Billing events đã tự động capture:\n• INBOUND_HANDLING (khi RECEIVED)\n• OUTBOUND_HANDLING (khi SHIPPED)\n• Daily storage snapshot (EOD 23:59)',
        placement: 'bottom',
      },
      {
        id: 'e2e-10',
        route: '/app/billing/invoices',
        target: '.section-title',
        title: 'Phase 5 — Billing: Generate & Lock DN',
        description: '💰 BILLING_OFC:\n1. Generate Draft DN\n2. Review charge lines\n3. Approve → Lock → Push ERP\n\n🏆 End-to-End Flow hoàn tất!\nHàng nhập → lưu kho → xuất → tính phí → push ERP.',
        placement: 'bottom',
      },
    ],
  },
]
