import { httpClient } from '@shared/api/httpClient'

const BASE_URL = '/inventory-control'

export const inventoryControlApi = {
  getOnHand: (params) => httpClient.get(`${BASE_URL}/on-hand`, { params }),
  getOnHandByItem: (itemId, params) => httpClient.get(`${BASE_URL}/on-hand/${itemId}`, { params }),
  getMovementHistory: (params) => httpClient.get(`${BASE_URL}/movement-history`, { params }),
  getMoveOrders: (params) => httpClient.get(`${BASE_URL}/moves`, { params }),
  getMoveOrderById: (id) => httpClient.get(`${BASE_URL}/moves/${id}`),
  createMoveOrder: (data) => httpClient.post(`${BASE_URL}/moves`, data),
  confirmMoveOrder: (id) => httpClient.post(`${BASE_URL}/moves/${id}/confirm`),
  executeMoveOrder: (id) => httpClient.post(`${BASE_URL}/moves/${id}/execute`),
  cancelMoveOrder: (id, data) => httpClient.post(`${BASE_URL}/moves/${id}/cancel`, data),
  getTransferOrders: (params) => httpClient.get(`${BASE_URL}/transfers`, { params }),
  getTransferOrderById: (id) => httpClient.get(`${BASE_URL}/transfers/${id}`),
  createTransferOrder: (data) => httpClient.post(`${BASE_URL}/transfers`, data),
  releaseTransferOrder: (id) => httpClient.post(`${BASE_URL}/transfers/${id}/release`),
  shipTransferOrder: (id, data) => httpClient.post(`${BASE_URL}/transfers/${id}/ship`, data),
  receiveTransferOrder: (id, data) => httpClient.post(`${BASE_URL}/transfers/${id}/receive`, data),
  closeTransferOrder: (id, data) => httpClient.post(`${BASE_URL}/transfers/${id}/close`, data),
  cancelTransferOrder: (id, data) => httpClient.post(`${BASE_URL}/transfers/${id}/cancel`, data),
  getStatusChanges: (params) => httpClient.get(`${BASE_URL}/status-changes`, { params }),
  createStatusChange: (data) => httpClient.post(`${BASE_URL}/status-changes`, data),
  executeStatusChange: (id) => httpClient.post(`${BASE_URL}/status-changes/${id}/execute`),
  cancelStatusChange: (id) => httpClient.post(`${BASE_URL}/status-changes/${id}/cancel`),
  getCycleCounts: (params) => httpClient.get(`${BASE_URL}/cycle-counts`, { params }),
  getCycleCountById: (id) => httpClient.get(`${BASE_URL}/cycle-counts/${id}`),
  createCycleCount: (data) => httpClient.post(`${BASE_URL}/cycle-counts`, data),
  releaseCycleCount: (id) => httpClient.post(`${BASE_URL}/cycle-counts/${id}/release`),
  submitCycleCount: (id, data) => httpClient.post(`${BASE_URL}/cycle-counts/${id}/submit`, data),
  approveCycleCount: (id) => httpClient.post(`${BASE_URL}/cycle-counts/${id}/approve`),
  postCycleCount: (id) => httpClient.post(`${BASE_URL}/cycle-counts/${id}/post`),
  getAdjustments: (params) => httpClient.get(`${BASE_URL}/adjustments`, { params }),
  createAdjustment: (data) => httpClient.post(`${BASE_URL}/adjustments`, data),
  submitAdjustment: (id) => httpClient.post(`${BASE_URL}/adjustments/${id}/submit`),
  approveAdjustment: (id) => httpClient.post(`${BASE_URL}/adjustments/${id}/approve`),
  postAdjustment: (id) => httpClient.post(`${BASE_URL}/adjustments/${id}/post`),
}
