export { IntegrationLayout } from './IntegrationLayout'
export { MonitoringPage } from './MonitoringPage'
export { AlertsPage } from './AlertsPage'
export { WeighbridgePage } from './WeighbridgePage'
export { ChannelsPage } from './ChannelsPage'
export { OcrPage } from './OcrPage'
export { OcrDetailPage } from './OcrDetailPage'
