import { PrismaClient, InventoryTransType, InventoryStage } from '@prisma/client';

const prisma = new PrismaClient();

const inventoryEventMappings = [
  // ===== INBOUND POSTINGS (M4 → M3) =====
  {
    eventCode: 'PO_CONFIRMED',
    sourceModule: 'M4',
    sourceObject: 'PURCHASE_ORDER',
    triggerState: 'CONFIRMED',
    transType: 'RECEIPT' as InventoryTransType,
    stage: 'EXPECTED' as InventoryStage,
    affectPhysical: false,
    affectOrdered: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'PO confirmed — increases inboundOrderedQty',
  },
  {
    eventCode: 'RECEIPT_CREATED',
    sourceModule: 'M4',
    sourceObject: 'RECEIPT',
    triggerState: 'CREATED',
    transType: 'RECEIPT' as InventoryTransType,
    stage: 'REGISTERED' as InventoryStage,
    affectPhysical: false,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Receipt document created — no bucket change, audit trail only',
  },
  {
    eventCode: 'GOODS_RECEIVED',
    sourceModule: 'M4',
    sourceObject: 'RECEIPT',
    triggerState: 'RECEIVED',
    transType: 'RECEIPT' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Goods received — +physicalQty, -inboundOrderedQty',
  },
  {
    eventCode: 'PUTAWAY_COMPLETED',
    sourceModule: 'M7',
    sourceObject: 'WORK_LINE',
    triggerState: 'COMPLETED',
    transType: 'MOVE' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Move from receiving to storage — net zero total physicalQty',
  },

  // ===== OUTBOUND POSTINGS (M5 → M3) =====
  {
    eventCode: 'SO_CONFIRMED',
    sourceModule: 'M5',
    sourceObject: 'SALES_ORDER',
    triggerState: 'CONFIRMED',
    transType: 'ISSUE' as InventoryTransType,
    stage: 'EXPECTED' as InventoryStage,
    affectPhysical: false,
    affectOrdered: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'SO confirmed — +outboundOrderedQty',
  },
  {
    eventCode: 'ALLOCATION_CREATED',
    sourceModule: 'M5',
    sourceObject: 'SHIPMENT',
    triggerState: 'ALLOCATED',
    transType: 'ISSUE' as InventoryTransType,
    stage: 'ALLOCATED' as InventoryStage,
    affectPhysical: false,
    affectOrdered: false,
    affectHold: true,
    reversible: true,
    activeFlag: true,
    notes: 'Allocation created — +allocatedQty (reduces available)',
  },
  {
    eventCode: 'ALLOCATION_RELEASED',
    sourceModule: 'M5',
    sourceObject: 'SHIPMENT',
    triggerState: 'DEALLOCATED',
    transType: 'ISSUE' as InventoryTransType,
    stage: 'DE_ALLOCATED' as InventoryStage,
    affectPhysical: false,
    affectOrdered: false,
    affectHold: true,
    reversible: false,
    activeFlag: true,
    notes: 'Allocation released — -allocatedQty (restores available)',
  },
  {
    eventCode: 'PICK_CONFIRMED',
    sourceModule: 'M7',
    sourceObject: 'WORK_LINE',
    triggerState: 'COMPLETED',
    transType: 'ISSUE' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Pick confirmed — internal move from storage to staging/picking zone',
  },
  {
    eventCode: 'LOAD_CONFIRMED',
    sourceModule: 'M5',
    sourceObject: 'SHIPMENT',
    triggerState: 'LOADED',
    transType: 'ISSUE' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Load confirmed — internal move from staging to dock/vehicle',
  },
  {
    eventCode: 'SHIP_CONFIRMED',
    sourceModule: 'M5',
    sourceObject: 'SHIPMENT',
    triggerState: 'SHIPPED',
    transType: 'ISSUE' as InventoryTransType,
    stage: 'DEDUCTED' as InventoryStage,
    affectPhysical: true,
    affectOrdered: true,
    affectHold: true,
    reversible: true,
    activeFlag: true,
    notes: 'Ship confirmed — -physicalQty, -allocatedQty, -outboundOrderedQty',
  },

  // ===== TRANSFER POSTINGS (M6 → M3) =====
  {
    eventCode: 'TRANSFER_ORDER_CONFIRMED',
    sourceModule: 'M6',
    sourceObject: 'TRANSFER',
    triggerState: 'CONFIRMED',
    transType: 'TRANSFER_ISSUE' as InventoryTransType,
    stage: 'EXPECTED' as InventoryStage,
    affectPhysical: false,
    affectOrdered: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Transfer order confirmed — +outboundOrderedQty at source warehouse',
  },
  {
    eventCode: 'TRANSFER_ISSUED',
    sourceModule: 'M6',
    sourceObject: 'TRANSFER',
    triggerState: 'SHIPPED',
    transType: 'TRANSFER_ISSUE' as InventoryTransType,
    stage: 'DEDUCTED' as InventoryStage,
    affectPhysical: true,
    affectOrdered: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Transfer issued — -physicalQty, -outboundOrderedQty at source warehouse',
  },
  {
    eventCode: 'TRANSFER_RECEIVED',
    sourceModule: 'M6',
    sourceObject: 'TRANSFER',
    triggerState: 'RECEIVED',
    transType: 'TRANSFER_RECEIPT' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Transfer received — +physicalQty at destination warehouse',
  },

  // ===== VAS POSTINGS (M9 → M3) =====
  {
    eventCode: 'VAS_ORDER_CONFIRMED',
    sourceModule: 'M9',
    sourceObject: 'VAS_ORDER',
    triggerState: 'CONFIRMED',
    transType: 'ISSUE' as InventoryTransType,
    stage: 'EXPECTED' as InventoryStage,
    affectPhysical: false,
    affectOrdered: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'VAS order confirmed — +outboundOrderedQty for raw material',
  },
  {
    eventCode: 'VAS_CONSUMED',
    sourceModule: 'M9',
    sourceObject: 'VAS_ORDER',
    triggerState: 'COMPLETED',
    transType: 'ISSUE' as InventoryTransType,
    stage: 'DEDUCTED' as InventoryStage,
    affectPhysical: true,
    affectOrdered: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'VAS consume — -physicalQty (raw material), -outboundOrderedQty',
  },
  {
    eventCode: 'VAS_PRODUCED',
    sourceModule: 'M9',
    sourceObject: 'VAS_ORDER',
    triggerState: 'COMPLETED',
    transType: 'RECEIPT' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'VAS produce — +physicalQty (finished goods)',
  },
  {
    eventCode: 'VAS_WASTE',
    sourceModule: 'M9',
    sourceObject: 'VAS_ORDER',
    triggerState: 'COMPLETED',
    transType: 'ADJUSTMENT' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'VAS waste — -physicalQty (loss/waste)',
  },

  // ===== INVENTORY CONTROL POSTINGS (M6 → M3) =====
  {
    eventCode: 'MOVE_COMPLETED',
    sourceModule: 'M6',
    sourceObject: 'INVENTORY_CONTROL',
    triggerState: 'COMPLETED',
    transType: 'MOVE' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Internal move within warehouse — net zero impact',
  },
  {
    eventCode: 'STATUS_CHANGE_CONFIRMED',
    sourceModule: 'M6',
    sourceObject: 'INVENTORY_CONTROL',
    triggerState: 'CONFIRMED',
    transType: 'STATUS_CHANGE' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Status reclass — qty unchanged, status dimension changes',
  },
  {
    eventCode: 'ADJUSTMENT_APPROVED',
    sourceModule: 'M6',
    sourceObject: 'INVENTORY_CONTROL',
    triggerState: 'APPROVED',
    transType: 'ADJUSTMENT' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Manual adjustment — reason code required',
  },
  {
    eventCode: 'COUNT_GAIN_RECONCILED',
    sourceModule: 'M6',
    sourceObject: 'CYCLE_COUNT',
    triggerState: 'RECONCILED',
    transType: 'ADJUSTMENT' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Cycle count gain — delta positive adjustment',
  },
  {
    eventCode: 'COUNT_LOSS_RECONCILED',
    sourceModule: 'M6',
    sourceObject: 'CYCLE_COUNT',
    triggerState: 'RECONCILED',
    transType: 'ADJUSTMENT' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: false,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Cycle count loss — delta negative adjustment',
  },

  // ===== BACKWARD COMPAT: Old event codes (deprecated, will be removed) =====
  {
    eventCode: 'RECEIPT_RECEIVED',
    sourceModule: 'M4',
    sourceObject: 'RECEIPT',
    triggerState: 'RECEIVED',
    transType: 'RECEIPT' as InventoryTransType,
    stage: 'PHYSICAL' as InventoryStage,
    affectPhysical: true,
    affectOrdered: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'DEPRECATED — use GOODS_RECEIVED instead. Kept for backward compatibility.',
  },
  {
    eventCode: 'SHIPMENT_SHIPPED',
    sourceModule: 'M5',
    sourceObject: 'SHIPMENT',
    triggerState: 'SHIPPED',
    transType: 'ISSUE' as InventoryTransType,
    stage: 'DEDUCTED' as InventoryStage,
    affectPhysical: true,
    affectOrdered: true,
    affectHold: true,
    reversible: true,
    activeFlag: true,
    notes: 'DEPRECATED — use SHIP_CONFIRMED instead. Kept for backward compatibility.',
  },
];

export async function seedInventoryEventMapping() {
  console.log('Seeding inventory event mappings...');

  for (const mapping of inventoryEventMappings) {
    await prisma.inventoryEventMapping.upsert({
      where: { eventCode: mapping.eventCode },
      update: mapping,
      create: mapping,
    });
  }

  console.log(`Seeded ${inventoryEventMappings.length} inventory event mappings`);
}
