import { PrismaClient, InventoryTransType } from '@prisma/client';

const prisma = new PrismaClient();

const inventoryEventMappings = [
  {
    eventCode: 'RECEIPT_RECEIVED',
    sourceModule: 'M4',
    sourceObject: 'RECEIPT',
    triggerState: 'RECEIVED',
    transType: InventoryTransType.RECEIPT_IN,
    affectPhysical: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Post inbound at RECEIVED state - adds physical qty to receiving location',
  },
  {
    eventCode: 'PUTAWAY_COMPLETED',
    sourceModule: 'M7',
    sourceObject: 'WORK_LINE',
    triggerState: 'COMPLETED',
    transType: InventoryTransType.MOVE,
    affectPhysical: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Move from receiving dim to storage dim',
  },
  {
    eventCode: 'SHIPMENT_SHIPPED',
    sourceModule: 'M5',
    sourceObject: 'SHIPMENT',
    triggerState: 'SHIPPED',
    transType: InventoryTransType.SHIPMENT_OUT,
    affectPhysical: true,
    affectHold: true,
    reversible: true,
    activeFlag: true,
    notes: 'Post outbound at SHIPPED state - deducts physical qty and releases hold',
  },
  {
    eventCode: 'MOVE_COMPLETED',
    sourceModule: 'M6',
    sourceObject: 'INVENTORY_CONTROL',
    triggerState: 'COMPLETED',
    transType: InventoryTransType.MOVE,
    affectPhysical: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Internal move within warehouse - net zero impact',
  },
  {
    eventCode: 'STATUS_CHANGE_CONFIRMED',
    sourceModule: 'M6',
    sourceObject: 'INVENTORY_CONTROL',
    triggerState: 'CONFIRMED',
    transType: InventoryTransType.STATUS_CHANGE,
    affectPhysical: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Status reclass - qty unchanged, status dimension changes',
  },
  {
    eventCode: 'ADJUSTMENT_APPROVED',
    sourceModule: 'M6',
    sourceObject: 'INVENTORY_CONTROL',
    triggerState: 'APPROVED',
    transType: InventoryTransType.ADJUSTMENT,
    affectPhysical: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Manual adjustment - reason code required',
  },
  {
    eventCode: 'COUNT_GAIN_RECONCILED',
    sourceModule: 'M6',
    sourceObject: 'CYCLE_COUNT',
    triggerState: 'RECONCILED',
    transType: InventoryTransType.COUNT_GAIN,
    affectPhysical: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Cycle count gain - delta positive adjustment',
  },
  {
    eventCode: 'COUNT_LOSS_RECONCILED',
    sourceModule: 'M6',
    sourceObject: 'CYCLE_COUNT',
    triggerState: 'RECONCILED',
    transType: InventoryTransType.COUNT_LOSS,
    affectPhysical: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Cycle count loss - delta negative adjustment',
  },
  {
    eventCode: 'TRANSFER_SHIPPED',
    sourceModule: 'M6',
    sourceObject: 'TRANSFER',
    triggerState: 'SHIPPED',
    transType: InventoryTransType.TRANSFER_OUT,
    affectPhysical: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Transfer out from source warehouse',
  },
  {
    eventCode: 'TRANSFER_RECEIVED',
    sourceModule: 'M6',
    sourceObject: 'TRANSFER',
    triggerState: 'RECEIVED',
    transType: InventoryTransType.TRANSFER_IN,
    affectPhysical: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'Transfer in to destination warehouse',
  },
  {
    eventCode: 'VAS_CONSUME_COMPLETED',
    sourceModule: 'M9',
    sourceObject: 'VAS_ORDER',
    triggerState: 'COMPLETED',
    transType: InventoryTransType.VAS_CONSUME,
    affectPhysical: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'VAS consume bulk material',
  },
  {
    eventCode: 'VAS_PRODUCE_COMPLETED',
    sourceModule: 'M9',
    sourceObject: 'VAS_ORDER',
    triggerState: 'COMPLETED',
    transType: InventoryTransType.VAS_PRODUCE,
    affectPhysical: true,
    affectHold: false,
    reversible: true,
    activeFlag: true,
    notes: 'VAS produce bagged goods',
  },
];

export async function seedInventoryEventMapping() {
  console.log('Seeding inventory event mappings...');
  
  for (const mapping of inventoryEventMappings) {
    await prisma.inventoryEventMapping.upsert({
      where: { eventCode: mapping.eventCode },
      update: mapping,
      create: mapping,
    });
  }
  
  console.log(`Seeded ${inventoryEventMappings.length} inventory event mappings`);
}
