export enum WeighingType {
  WEIGH_IN = 'WEIGH_IN',
  WEIGH_OUT = 'WEIGH_OUT',
  TARE = 'TARE',
  GROSS_LINE = 'GROSS_LINE',
  MANUAL_ENTRY = 'MANUAL_ENTRY',
}

export enum DeviceStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  DEGRADED = 'DEGRADED',
}

export enum WeighEventProcessingStatus {
  RECEIVED = 'RECEIVED',
  VALIDATED = 'VALIDATED',
  LINKED = 'LINKED',
  DUPLICATE = 'DUPLICATE',
  FAILED = 'FAILED',
}

export enum CallbackStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  ACKED = 'ACKED',
  FAILED = 'FAILED',
}

export enum OcrStatus {
  UPLOADED = 'UPLOADED',
  EXTRACTING = 'EXTRACTING',
  EXTRACTED = 'EXTRACTED',
  REVIEW_REQUIRED = 'REVIEW_REQUIRED',
  CONFIRMED = 'CONFIRMED',
  LINKED = 'LINKED',
  REJECTED = 'REJECTED',
}

export enum OcrLinkMethod {
  AUTO_MATCHED = 'AUTO_MATCHED',
  OPERATOR_SELECTED = 'OPERATOR_SELECTED',
  OPERATOR_CREATED = 'OPERATOR_CREATED',
}

export enum SyncBatchStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  PARTIAL_SUCCESS = 'PARTIAL_SUCCESS',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  CONFLICTED = 'CONFLICTED',
}

export enum SyncEventStatus {
  RECEIVED = 'RECEIVED',
  DUPLICATE = 'DUPLICATE',
  DISPATCHED = 'DISPATCHED',
  APPLIED = 'APPLIED',
  CONFLICTED = 'CONFLICTED',
  FAILED = 'FAILED',
}

export enum ErpPushStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  ACK_SUCCESS = 'ACK_SUCCESS',
  ACK_FAILED = 'ACK_FAILED',
  RETRY_SCHEDULED = 'RETRY_SCHEDULED',
  DEAD_LETTER = 'DEAD_LETTER',
  CANCELLED = 'CANCELLED',
}

export enum AlertSeverity {
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
}

export enum AlertStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
  SUPPRESSED = 'SUPPRESSED',
}

export enum ChannelStatus {
  HEALTHY = 'HEALTHY',
  DEGRADED = 'DEGRADED',
  DOWN = 'DOWN',
}

export enum IntegrationChannel {
  WEIGHBRIDGE = 'WEIGHBRIDGE',
  OCR = 'OCR',
  MOBILE_SYNC = 'MOBILE_SYNC',
  ERP_PUSH = 'ERP_PUSH',
}

export enum SourceModule {
  M4 = 'M4',
  M5 = 'M5',
  M6 = 'M6',
  M7 = 'M7',
}

export enum AlertCode {
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',
  DEVICE_DEGRADED = 'DEVICE_DEGRADED',
  ERP_PUSH_FAILED = 'ERP_PUSH_FAILED',
  ERP_PUSH_DEAD_LETTER = 'ERP_PUSH_DEAD_LETTER',
  OCR_LOW_CONFIDENCE = 'OCR_LOW_CONFIDENCE',
  OCR_EXTRACTION_FAILED = 'OCR_EXTRACTION_FAILED',
  MOBILE_SYNC_CONFLICT = 'MOBILE_SYNC_CONFLICT',
  MOBILE_SYNC_FAILED = 'MOBILE_SYNC_FAILED',
  CALLBACK_FAILED = 'CALLBACK_FAILED',
}

export enum ReferenceType {
  RECEIPT = 'RECEIPT',
  SHIPMENT = 'SHIPMENT',
}
