export enum VasWoStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum VasPackagingOwnership {
  TVL_OWNED = 'TVL_OWNED',
  CLIENT_OWNED = 'CLIENT_OWNED',
}

export enum VasShiftCode {
  MORNING = 'MORNING',
  AFTERNOON = 'AFTERNOON',
  NIGHT = 'NIGHT',
}

export enum VasOutboxStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  DEAD = 'DEAD',
}

export enum VasStateAction {
  CREATE = 'CREATE',
  CONFIRM = 'CONFIRM',
  START = 'START',
  ADD_SESSION = 'ADD_SESSION',
  COMPLETE = 'COMPLETE',
  CANCEL = 'CANCEL',
}

export enum VasExceptionCode {
  VAS_WO_NOT_FOUND = 'VAS_WO_NOT_FOUND',
  VAS_INVALID_STATE = 'VAS_INVALID_STATE',
  VAS_DUPLICATE_EXTERNAL_ID = 'VAS_DUPLICATE_EXTERNAL_ID',
  VAS_INSUFFICIENT_BULK = 'VAS_INSUFFICIENT_BULK',
  VAS_INSUFFICIENT_PACKAGING = 'VAS_INSUFFICIENT_PACKAGING',
  VAS_INVALID_MATERIAL_BALANCE = 'VAS_INVALID_MATERIAL_BALANCE',
  VAS_REASON_REQUIRED = 'VAS_REASON_REQUIRED',
  VAS_RESERVATION_CONFLICT = 'VAS_RESERVATION_CONFLICT',
  VAS_ALREADY_COMPLETED = 'VAS_ALREADY_COMPLETED',
  VAS_ALREADY_CANCELLED = 'VAS_ALREADY_CANCELLED',
  VAS_SESSION_INVALID = 'VAS_SESSION_INVALID',
  VAS_PACKAGING_OWNER_INVALID = 'VAS_PACKAGING_OWNER_INVALID',
  VAS_OPTIMISTIC_LOCK_FAILED = 'VAS_OPTIMISTIC_LOCK_FAILED',
}
