/**
 * Module 7: Work Execution - Type Definitions
 */

const WORK_TYPES = {
  PUTAWAY: 'PUTAWAY',
  PICK: 'PICK',
  MOVE: 'MOVE',
  TRANSFER_PICK: 'TRANSFER_PICK',
  TRANSFER_PUT: 'TRANSFER_PUT',
};

const WORK_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const WORK_LINE_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
  CANCELLED: 'CANCELLED',
};

const STEP_TYPES = {
  PUT: 'PUT',
  PICK: 'PICK',
  MOVE: 'MOVE',
  TRANSFER_PICK: 'TRANSFER_PICK',
  TRANSFER_PUT: 'TRANSFER_PUT',
};

const POSTING_STATUS = {
  PENDING: 'PENDING',
  POSTED: 'POSTED',
  FAILED: 'FAILED',
};

const ASSIGNMENT_MODE = {
  SELF_CLAIM: 'SELF_CLAIM',
  DIRECTED: 'DIRECTED',
};

const ASSIGNMENT_ACTION = {
  CLAIM: 'CLAIM',
  RELEASE: 'RELEASE',
  REASSIGN: 'REASSIGN',
};

const TRIGGER_ACTION = {
  CREATE: 'CREATE',
  CLAIM: 'CLAIM',
  RELEASE: 'RELEASE',
  START: 'START',
  COMPLETE: 'COMPLETE',
  SKIP: 'SKIP',
  CANCEL: 'CANCEL',
  OVERRIDE: 'OVERRIDE',
};

const STATUS_OBJECT_TYPE = {
  HEADER: 'HEADER',
  LINE: 'LINE',
};

const EXCEPTION_TYPE = {
  SHORT_PICK: 'SHORT_PICK',
  LOCATION_MISMATCH: 'LOCATION_MISMATCH',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  SYNC_CONFLICT: 'SYNC_CONFLICT',
  POSTING_FAILED: 'POSTING_FAILED',
};

const EXCEPTION_SEVERITY = {
  INFO: 'INFO',
  WARN: 'WARN',
  BLOCKER: 'BLOCKER',
};

const EXCEPTION_STATUS = {
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
};

const SYNC_EVENT_TYPE = {
  START_LINE: 'START_LINE',
  COMPLETE_LINE: 'COMPLETE_LINE',
  SKIP_LINE: 'SKIP_LINE',
};

const SYNC_RESULT = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  DUPLICATE: 'DUPLICATE',
  CONFLICT: 'CONFLICT',
  REJECTED: 'REJECTED',
};

const SYNC_BATCH_STATUS = {
  RECEIVED: 'RECEIVED',
  PROCESSING: 'PROCESSING',
  PARTIAL: 'PARTIAL',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
};

const OUTBOX_STATUS = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  DEAD: 'DEAD',
};

const SOURCE_MODULE = {
  M4: 'M4',
  M5: 'M5',
  M6: 'M6',
  MANUAL: 'MANUAL',
};

const SOURCE_TYPE = {
  RECEIPT: 'RECEIPT',
  SHIPMENT: 'SHIPMENT',
  MOVE_ORDER: 'MOVE_ORDER',
  TRANSFER_ORDER: 'TRANSFER_ORDER',
};

const EVENT_TYPES = {
  WORK_CREATED: 'WORK_CREATED',
  WORK_CLAIMED: 'WORK_CLAIMED',
  WORK_RELEASED: 'WORK_RELEASED',
  WORK_STARTED: 'WORK_STARTED',
  WORK_COMPLETED: 'WORK_COMPLETED',
  WORK_CANCELLED: 'WORK_CANCELLED',
  LINE_STARTED: 'LINE_STARTED',
  LINE_COMPLETED: 'LINE_COMPLETED',
  LINE_SKIPPED: 'LINE_SKIPPED',
  LINE_CANCELLED: 'LINE_CANCELLED',
  POSTING_SUCCESS: 'POSTING_SUCCESS',
  POSTING_FAILED: 'POSTING_FAILED',
  EXCEPTION_RAISED: 'EXCEPTION_RAISED',
  EXCEPTION_RESOLVED: 'EXCEPTION_RESOLVED',
  SYNC_RECEIVED: 'SYNC_RECEIVED',
  SYNC_DUPLICATE: 'SYNC_DUPLICATE',
  SYNC_CONFLICT: 'SYNC_CONFLICT',
};

const CALLBACK_EVENT_TYPES = {
  PUTAWAY_COMPLETED: 'PUTAWAY_COMPLETED',
  PICK_COMPLETED: 'PICK_COMPLETED',
  MOVE_COMPLETED: 'MOVE_COMPLETED',
  TRANSFER_PICK_COMPLETED: 'TRANSFER_PICK_COMPLETED',
  TRANSFER_PUT_COMPLETED: 'TRANSFER_PUT_COMPLETED',
  WORK_CANCELLED: 'WORK_CANCELLED',
};

const LOCATION_TYPE_FOR_WORK = {
  PUTAWAY: { from: 'RECEIVING', to: 'STORAGE' },
  PICK: { from: 'STORAGE', to: 'STAGING' },
  MOVE: { from: null, to: null },
  TRANSFER_PICK: { from: 'STORAGE', to: 'STAGING' },
  TRANSFER_PUT: { from: 'RECEIVING', to: 'STORAGE' },
};

const SHORT_PICK_THRESHOLDS = {
  ALLOW_PCT: 2,
  WARN_PCT: 5,
};

module.exports = {
  WORK_TYPES,
  WORK_STATUS,
  WORK_LINE_STATUS,
  STEP_TYPES,
  POSTING_STATUS,
  ASSIGNMENT_MODE,
  ASSIGNMENT_ACTION,
  TRIGGER_ACTION,
  STATUS_OBJECT_TYPE,
  EXCEPTION_TYPE,
  EXCEPTION_SEVERITY,
  EXCEPTION_STATUS,
  SYNC_EVENT_TYPE,
  SYNC_RESULT,
  SYNC_BATCH_STATUS,
  OUTBOX_STATUS,
  SOURCE_MODULE,
  SOURCE_TYPE,
  EVENT_TYPES,
  CALLBACK_EVENT_TYPES,
  LOCATION_TYPE_FOR_WORK,
  SHORT_PICK_THRESHOLDS,
};
