export const REPORTING_CONSTANTS = {
  MAX_DATE_RANGE_DAYS: 92,
  MAX_PAGE_SIZE: 500,
  DEFAULT_PAGE_SIZE: 50,

  EXPORT_SYNC_THRESHOLD_ROWS: 5000,
  EXPORT_PDF_MAX_ROWS: 10000,
  EXPORT_CSV_MAX_ROWS: 100000,
  EXPORT_FILE_EXPIRY_HOURS: 24,

  DASHBOARD_CACHE_TTL_SECONDS: 60,
  BILLING_CACHE_TTL_SECONDS: 300,
  UTILIZATION_CACHE_TTL_SECONDS: 900,

  RECONCILIATION_IDEMPOTENCY_WINDOW_MINUTES: 10,
  GOLIVE_CHECK_IDEMPOTENCY_WINDOW_MINUTES: 5,
  EXPORT_IDEMPOTENCY_WINDOW_MINUTES: 5,

  PERMISSION_CODES: {
    DASHBOARD_READ: 'REPORTING.DASHBOARD.READ',
    INVENTORY_READ: 'REPORTING.INVENTORY.READ',
    BILLING_READ: 'REPORTING.BILLING.READ',
    AUDIT_READ: 'REPORTING.AUDIT.READ',
    RECONCILIATION_RUN: 'REPORTING.RECONCILIATION.RUN',
    RECONCILIATION_READ: 'REPORTING.RECONCILIATION.READ',
    RECONCILIATION_RESOLVE: 'REPORTING.RECONCILIATION.RESOLVE',
    GOLIVE_READ: 'REPORTING.GOLIVE.READ',
    GOLIVE_CHECK: 'REPORTING.GOLIVE.CHECK',
    GOLIVE_SIGNOFF: 'REPORTING.GOLIVE.SIGNOFF',
    EXPORT_CREATE: 'REPORTING.EXPORT.CREATE',
    EXPORT_READ: 'REPORTING.EXPORT.READ',
  },

  ERROR_CODES: {
    REPORT_NOT_FOUND: 'RPT_NOT_FOUND',
    EXPORT_JOB_NOT_FOUND: 'EXPORT_JOB_NOT_FOUND',
    EXPORT_JOB_EXPIRED: 'EXPORT_JOB_EXPIRED',
    EXPORT_ROW_LIMIT_EXCEEDED: 'EXPORT_ROW_LIMIT_EXCEEDED',
    RECON_RUN_NOT_FOUND: 'RECON_RUN_NOT_FOUND',
    RECON_RESULT_NOT_FOUND: 'RECON_RESULT_NOT_FOUND',
    RECON_ALREADY_RESOLVED: 'RECON_ALREADY_RESOLVED',
    GOLIVE_GATE_NOT_FOUND: 'GOLIVE_GATE_NOT_FOUND',
    GOLIVE_SIGNOFF_NOT_ALLOWED: 'GOLIVE_SIGNOFF_NOT_ALLOWED',
    GOLIVE_WAIVER_REQUIRED: 'GOLIVE_WAIVER_REQUIRED',
    SCOPE_ACCESS_DENIED: 'SCOPE_ACCESS_DENIED',
    DATE_RANGE_EXCEEDED: 'DATE_RANGE_EXCEEDED',
    INVALID_FILTER: 'INVALID_FILTER',
  },
} as const;
